name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: ananthb
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build release artifacts
        run: nix build .#release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            result/*
          generate_release_notes: true
